add_newline = false

[directory]
truncation_length = 8
style = "cyan"

[git_status]
# Disable style due to https://github.com/starship/starship/issues/290
style = ""
staged.style = "green"
staged_count.enabled = true
staged_count.style = "green"

[line_break]
disabled = true
