add_newline = false

[directory]
truncation_length = 8
style = "cyan"

[git_status]
staged.style = "green"
staged_count.enabled = true
staged_count.style = "green"

# Issue https://github.com/starship/starship/issues/290 seems to be
# reproducible disabling line_break.
# [line_break]
# disabled = true
